[
    {
        "name": "Point.ByCoordinates",
        "fullName": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
        "creationStrategy": "NATIVE_WITH_OVERLOAD",
        "overloads": [
            {
                "id": "2D",
                "fullName": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
                "inputs": [
                    "x",
                    "y"
                ]
            },
            {
                "id": "3D",
                "fullName": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
                "inputs": [
                    "x",
                    "y",
                    "z"
                ]
            }
        ],
        "inputs": [
            "x",
            "y",
            "z"
        ]
    },
    {
        "name": "Sphere.ByCenterPointRadius",
        "fullName": "Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
        "creationStrategy": "NATIVE_DIRECT",
        "inputs": [
            "centerPoint",
            "radius"
        ]
    },
    {
        "name": "Cuboid.ByLengths",
        "fullName": "Autodesk.DesignScript.Geometry.Cuboid.ByLengths@double,double,double",
        "creationStrategy": "NATIVE_DIRECT",
        "inputs": [
            "width",
            "length",
            "height"
        ]
    },
    {
        "name": "Solid.Difference",
        "fullName": "Autodesk.DesignScript.Geometry.Solid.Difference@Autodesk.DesignScript.Geometry.Solid,Autodesk.DesignScript.Geometry.Solid",
        "creationStrategy": "NATIVE_DIRECT",
        "inputs": [
            "solid",
            "other"
        ]
    }
]